version: "3"

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cognitivo/backend-api
    working_dir: /app
    ports:
      - 5000:5000
    env_file:
      - .env
    healthcheck:
      test: wget -q -T 90 -O /dev/null http://0.0.0.0:3000/ || exit 1
      interval: 5m
      timeout: 30s
